### PR TITLE
Sanity Check + Scaling

### PR DESCRIPTION
**Pull request by Kayala47**
All of the models now create a csv of predicted values, and we plot those and save them as images so we can compare the procedurally generated plots vs the model's generated plots.

Working on adding gallop next!

### CODE REVIEW

**Review by anthonyjclark — COMMENTED** [review]
A few thoughts:

1. It would be easier to analyze the plots if "actual" and "predicted" were on top of each other. For example, FL A1 DF actual in the same subfigure as FL A1 DF predicted.
2. Any idea why the model is having trouble getting all DF2s to output zero?
3. In general, the network outputs seem to be poor. Could it be batch normalization?

Overall, this is fantastic work.

**Comment by anthonyjclark** [comment]
We might try using https://review.github.io/ to view this in 3D. Let me know if that is something you want to tackle.

**Comment by Kayala47** [comment]
Sounds good! I'll see if I can merge those two and then work on getting the model working. Any hints on batch normalization I should try out? 

I'm not really sure about DF 2, but I'll do some investigating and see if something is configured wrong maybe.

Also, I'd be happy to check out the 3D visualization once I'm done with that!

**Comment by anthonyjclark** [comment]
> Sounds good! I'll see if I can merge those two and then work on getting the model working.

I'd look into combining the two dataframes (actual and predicted) and then maybe using a `groupby`.


> Any hints on batch normalization I should try out?

I'd start by trying **without** any batch normalization. Try these:

- without batch norm without dropout
- with batch norm without dropout (done, doesn't seem to work)
- without batch norm with dropout
- with dropout and batch norm

> Also, I'd be happy to check out the 3D visualization once I'm done with that!

Let me know if you want an overview of that process.

**Comment by Kayala47** [comment]
In addition to the sanity checks, I've also scaled the layers of the model based on the average range (the name we gave to max-min/2). Ray stuff is on a different branch :)


(Shouldn't have closed - I was trying to add all the new commits)

**Pull request merged**
